/* Generated by Formulize from the Appearance settings in the Formulize admin UI.
 * Do not edit by hand: this file is regenerated whenever the settings are saved. */
<{if $fontUrl}>@import url("<{$fontUrl}>");
<{/if}>
<{if $overrides}>:root {
<{foreach from=$overrides key=token item=value}>  <{$token}>: <{$value}>;
<{/foreach}>}
<{/if}>
