title: Improvise. Organize. Customize.
logo: /assets/img/formulize-logo.png
description: Your very own database. 100% free and open source.
markdown: kramdown
baseurl: /
url: https://formulize.org/
permalink: /:title/
repository: jegelstaff/formulize
plugins:
  - breadcrumbs
  - jekyll-github-metadata
  - jekyll-redirect-from
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
