title: Improvise. Organize. Customize.
logo: /assets/img/formulize-logo.png
description: Your very own database. 100% free and open source.
markdown: kramdown
baseurl: /
url: https://formulize.org/
permalink: /:title/
