# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :jekyll_plugins do
  gem "breadcrumbs"
	gem "jekyll-github-metadata"
	gem "jekyll-redirect-from"
	gem "jekyll-paginate"
	gem "jekyll-feed"
end
