name: e2e test suite

on:
  push:
    branches:
      - master

jobs:
  e2e-test-run:
    if: |
      (contains(github.event.push.head_commit.message, '[SKIP TEST]')
      || contains(github.event.push.head_commit.message, '[SKIP TESTS]'))
      == false
    uses: ./.github/workflows/e2e-test-manual.yml
    with:
      ref: ${{ github.event.push.after }}

