name: e2e test suite

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  e2e-test-run:
    if: |
      !contains(join(github.event.commits.*.message, ' '), '[SKIP TEST]')
      && !contains(join(github.event.commits.*.message, ' '), '[SKIP TESTS]')
    uses: ./.github/workflows/e2e-test-manual.yml
    with:
      ref: ${{ github.sha }}
